version: "3.8"

services:
  backend:
    build: ./todo
    ports:
      - "8000:8000"
    volumes:
      - ./todo/db.sqlite3:/app/db.sqlite3

  frontend:
    build: ./front
    ports:
      - "8080:8080"
    depends_on:
      - backend
